### ISSUE TITLE
error in image in readme.md file

### ISSUE THREAD

**Issue by DrShunts** [ergolabs/ergo-dex#2]
I believe the titles bid and ask are transposed in  the image img/OrderBook.png. This is only a small thing but may confuse some people.

![orderbook](https://user-images.githubusercontent.com/84947449/119918607-1c006480-bfac-11eb-94c8-1eaad1a27a22.jpg)

**Comment by oskin1** [comment]
The problem is that actually ASKs sorted in the opposite direction in order-book. Thanks @DrShunts for the pointer.
